version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  allow:
    - dependency-type: "direct"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "chrono"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
