[project]
name = "NREL-transmission"
authors = [
  "Guilherme Castelão <gpimenta@nrel.gov>",
  "Paul Pinchuk <ppinchuk@nrel.gov>",
]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.0.1"

[tasks]

[dependencies]
rust = ">=1.85.0,<1.86"
