name: Documentation Improvement
description: Report wrong, missing, or incomplete reVRt documentation
type: Task
labels: [documentation, enhancement]

body:
  - type: checkboxes
    attributes:
      label: reVRt version checks
      options:
        - label: >
            I have checked that the issue still exists on the latest versions of the docs
            on `main` [here](https://nrel.github.io/reVRt/)
          required: true
  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation,
      # placeholder: https://nrel.github.io/gaps/_autosummary/gaps.config.load_config.html#gaps.config.load_config
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs to be fixed/improved.
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please provide a suggested fix for the wrong, missing, or incomplete documentation.
    validations:
      required: true
