name: Rust checks

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.45.0
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run cargo check
        run: |
          pixi run --frozen cargo check --workspace

  lints:
    # Only run tests if code looks OK
    needs: check
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.45.0
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run cargo fmt
        run: |
          pixi run --frozen cargo fmt --all --check

      - name: Run cargo clippy
        run: |
          pixi run --frozen cargo clippy --all-features --tests -- -D warnings

  test:
    # Only run tests if code looks OK
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [beta, stable, windows, macos]
        include:
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: stable
            os: ubuntu-latest
            rust: stable
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.47.0
          cache: true
          frozen: true

      - run: pixi install

      - run: pixi run python --version

      - run: pixi run which python

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: pixi run --frozen cargo test --workspace --no-fail-fast
        env:
          PYTHON_SYS_EXECUTABLE: ${{ github.workspace }}/.pixi/envs/default/bin/python
